In [1]:
import numpy as np

## Creating Matrices

In [5]:
two_dim = np.array([
    [2, -3, 1],
    [2, 0, -1],
    [1, 4, 5]
])

# 2 x 2 x 3
three_dim = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    
    [[7, 8, 9], 
     [10, 11, 12]]
])

print("2D MATRIX:")
print(two_dim.shape)
print(two_dim.ndim)
print("\n3D MATRIX:")
print(three_dim.shape)
print(three_dim.ndim)

2D MATRIX:
(3, 3)
2

3D MATRIX:
(2, 2, 3)
3


## Rendering

In [12]:
my_matrix = np.array([
    [["WOG", "WG", "WGR"], 
     ["OG", "G", "RG"],
     [7, 8, 9]],
    
    [[10, 11, 12], 
     [13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21], 
     [22, 23, 24],
     [25, 26, 27]],
])

In [ ]:
index = 0
cube = [None] * 27

# We have an individual matrix for each cubie
for x in [-1, 0, 1]:
    for y in [-1, 0, 1]:
        for z in [-1, 0, 1]:
            # create a new matrix for a cubie
            matrix = False
            cube[index] = Cubie(matrix, x, y, z)
            index += 1

In [ ]:
# Go through each cubie and rotate if on correct plane


In [20]:
angle = np.radians(90)

R_yz = np.array([
    [1, 0,             0],
    [0, np.cos(angle), -np.sin(angle)],
    [0, np.sin(angle), np.cos(angle)]
])

def turn_X(angle):
    rotation_vec = np.array([
        [1, 0,             0],
        [0, np.cos(angle), -np.sin(angle)],
        [0, np.sin(angle), np.cos(angle)]
    ])
    
    return np.dot(my_matrix, rotation_vec.T)

rotated_matrix = np.zeros_like(my_matrix)

rotated_matrix_copy = turn_X(90)

for x in range(3):
    rotated_matrix[x] = np.dot(my_matrix[x], R_yz.T)
    
print(my_matrix)
print()
print(rotated_matrix)
print()
print(rotated_matrix_copy)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[[  1  -3   2]
  [  4  -6   5]
  [  7  -9   8]]

 [[ 10 -12  11]
  [ 13 -15  14]
  [ 16 -18  17]]

 [[ 19 -21  20]
  [ 22 -24  23]
  [ 25 -27  26]]]

[[[  1.          -3.57813722   0.44377248]
  [  4.          -7.60434806   1.78154162]
  [  7.         -11.6305589    3.11931076]]

 [[ 10.         -15.65676974   4.45707991]
  [ 13.         -19.68298058   5.79484905]
  [ 16.         -23.70919142   7.13261819]]

 [[ 19.         -27.73540226   8.47038733]
  [ 22.         -31.7616131    9.80815648]
  [ 25.         -35.78782394  11.14592562]]]


In [ ]:
class Cubie:
    def __init__(self, edge_type, colors):
        self.edge_type = edge_type
        self.colors = colors
        
class Cube:
    def __init__(self):
        self.cube = initialize_cube()
        
    def initialize_cube():
        cube = [None] * (3*3*3)
        index = 0
        for x in [-1, 0, 1]:
            for y in [-1, 0, 1]:
                for z in [-1, 0, 1]:
                    edge_type = None
                    
                    # Discern center vs edge vs corner
                    location = [x, y, z]
                    
                    if (x == 0 and y == 0) or (x == 0 and z == 0) or (y == 0 and z == 0):
                        # i.e. (1 0 0) or (0 1 0)
                        edge_type = 'center'
                    elif 0 in location:
                        # i.e. (1 0 -1) or (0, 1, 1)
                        edge_type = 'edge'
                    else:
                        # anything else is a corner
                        edge_type = 'corner'
                        
                    # x=1 --> Green
                    # x=0 --> Red or orange
                    # x=
                    
                    cube[index] = Cubie()
                    index += 1

# Now looking at example

In [56]:
import math
import pandas as pd

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

def rotate_x(x, y, z, degrees):
    new_x = x
    new_y = round(y*math.cos(math.radians(degrees)) - y*math.sin(math.radians(degrees)))
    new_z = round(-z*math.sin(math.radians(degrees)) + z*math.cos(math.radians(degrees)))
    
    return (new_x, new_y, new_z)

def rotate_y(x, y, z, degrees):
    new_x = round(x*math.cos(math.radians(degrees)) + z*math.sin(math.radians(degrees)))
    new_y = y
    new_z = round(-z*math.sin(math.radians(degrees)) + z*math.cos(math.radians(degrees)))
    
    return (new_x, new_y, new_z)

def rotate_z(x, y, z, degrees):
    new_x = round(x*math.cos(math.radians(degrees)) - x*math.sin(math.radians(degrees)))
    new_y = round(y*math.sin(math.radians(degrees)) + y*math.cos(math.radians(degrees)))
    new_z = z
    
    return (new_x, new_y, new_z)


results_dict = {}
for _x in [-1, 0, 1]:
    for _y in [-1, 0, 1]:
        for _z in [-1, 0, 1]:
            results_dict[(_x, _y, _z)] = [rotate_x(_x,_y,_z, 90), rotate_y(_x,_y,_z, 90), rotate_z(_x,_y,_z, 90)]

df = pd.DataFrame.from_dict(results_dict,orient='index').transpose()
display(df[(-1, -1, -1)])

0     (-1, 1, 1)
1    (-1, -1, 1)
2    (1, -1, -1)
Name: (-1, -1, -1), dtype: object